name: markdown_styled_widget
description: A new Flutter plugin project.
version: 0.0.1
repository: https://github.com/Willsem/markdown_styled_widget

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_html: ^2.2.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.markdown_styled_widget.markdown_styled_widget
        pluginClass: MarkdownStyledWidgetPlugin
      ios:
        pluginClass: MarkdownStyledWidgetPlugin
      web:
        pluginClass: MarkdownStyledWidgetWeb
        fileName: markdown_styled_widget_web.dart
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: IbarraRealNova
      fonts:
        - asset: fonts/IbarraRealNova/IbarraRealNova-Regular.ttf
        - asset: fonts/IbarraRealNova/IbarraRealNova-Italic.ttf
          style: italic
        - asset: fonts/IbarraRealNova/IbarraRealNova-Bold.ttf
          weight: 700
        - asset: fonts/IbarraRealNova/IbarraRealNova-BoldItalic.ttf
          style: italic
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
